### ISSUE TITLE
Use of SQLAlchemy `relationship` will load full collection in to memory

### ISSUE THREAD

**Issue by JamesGardiner** [ONSdigital/ras-party#61]
In `models.py` SQLAlchemy's `relationship` method is used to backpopulate other tables. This will load the entire related collection in to memory, which will be constrained in a CloudFoundry environment, especially as the collections grow with more RUs.

Using dynamic loading could be a safer approach https://www.codepowered.com/manuals/SQLAlchemy-0.6.9-doc/html/orm/collections.html#working-with-large-collections

**Comment by jonmorphic** [comment]
At present time (BRES), the business<->respondent relationship is expected to mostly have cardinality 1<->1, or at worst n<->n where n is small. Agree it's worth considering future growth, including whether the schema is generally fit-for-purpose for further types of survey.

**Comment by JamesGardiner** [comment]
@jonmorphic - is this the case across other RAS services where the same `relationship` method is used?

**Comment by jonmorphic** [comment]
Currently, two other RAS services make use of SQLAlchemy: ras-secure-messaging and ras-collection-instrument. I think the collection instrument service is the only one which has been known to manifest an issue due to relationship loading, both due to the high cardinality of the relationship and the large size of the persisted data. I'd recommend the design of that service is inappropriate and ought to be revisited in any case. The same might be said of ras-party, for slightly different (but overlapping) reasons. I'm not sure if there's an outstanding issue for which lazy relationship loading would be a useful workaround, worth keeping an eye on.

**Comment by jonmorphic** [comment]
I'd add to this, the relationship loading is lazy, so the related entities are only loaded into memory if actually accessed.
